name: yuki-no

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  workflow_dispatch: # Manual trigger

permissions:
  contents: write
  issues: write
  actions: read
  pull-requests: write

jobs:
  yuki-no:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      # https://github.com/Gumball12/yuki-no/
      - uses: Gumball12/yuki-no@wip
        env:
          YUKI_NO_BATCH_PR_ROOT_DIR: docs
          YUKI_NO_BATCH_PR_EXCLUDE: |
            **/guide/migration*.md
            **/package.json
            **/.vitepress/config.ts
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          head-repo: https://github.com/vitejs/vite.git
          track-from: a46f11a6c218f74b08ffb3e33a25c2ce02ba6643
          include: |
            docs/**
          plugins: |
            @yuki-no/plugin-release-tracking@latest
            @yuki-no/plugin-batch-pr@latest
